name: Distcheck

on: 
  push:
  pull_request:

env:
  JOBS: 2

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install autoconf automake
          cd /tmp
          wget https://ftpmirror.gnu.org/libtool/libtool-2.5.4.tar.gz
          tar xf libtool-2.5.4.tar.gz
          cd libtool-2.5.4
          ./configure
          make -j $JOBS
          sudo make install 
      - name: Configure
        run: |
          autoreconf -ivf
          ASAN_OPTIONS=detect_leaks=0 CFLAGS="-fsanitize=address" ./configure --enable-debug
      - name: Check
        run: ASAN_OPTIONS=detect_leaks=0 make -j $JOBS check
      - name: Distcheck
        run: make -j $JOBS distcheck
  macos:
    runs-on: macos-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: brew install autoconf automake libomp libtool
      - name: Configure
        run: |
          autoreconf -i
          export CPATH=$(brew --prefix)/opt/libomp/include
          export LIBRARY_PATH=$(brew --prefix)/opt/libomp/lib
          ./configure --enable-openmp --enable-debug

      - name: Check
        run: |
          export CPATH=$(brew --prefix)/opt/libomp/include
          export LIBRARY_PATH=$(brew --prefix)/opt/libomp/lib
          make -j $JOBS check
      - name: Distcheck
        run: |
          export CPATH=$(brew --prefix)/opt/libomp/include
          export LIBRARY_PATH=$(brew --prefix)/opt/libomp/lib
          make -j $JOBS distcheck
  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-autotools
            mingw-w64-x86_64-libtool
            mingw-w64-x86_64-pkg-config
            autoconf
            automake
            make
      - name: Configure
        run: |
          autoreconf -i
          ./configure --enable-debug

      - name: Check
        run: make -j $JOBS check
      - name: Distcheck
        run: make -j $JOBS distcheck
